mqtt:
  enabled: false

go2rtc:
  streams:
    pi_cam:
      - rtsp://<pi_cam_tailscale_ip>:8554/high # PI cam tailscale IP
  webrtc:
    candidates:
      - <frigate_server_tailscale_ip>:8555 # Frigate/this server tailscale IP
      - stun:8555

cameras:
  pi_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<pi_cam_tailscale_ip>:8554/low # PI cam tailscale IP
          roles:
            - detect
        - path: rtsp://<pi_cam_tailscale_ip>:8554/high # PI cam tailscale IP
          roles:
            - record
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    review:
      alerts:
        cutoff_time: 40
      detections:
        cutoff_time: 30

    record:
      enabled: true
      continuous:
        days: 7 # Continuous recording will be retained for 7 days - turn it to 0, if you don't want continuous recording.
      motion:
        days: 7 # Any segment containing motion will be retained for 7 days.
      alerts:
        pre_capture: 5
        post_capture: 5
        retain:
          days: 7 # Any segment containing alerts - not any useful object in the shot will be retained for 7 days.
          mode: motion
      detections:
        pre_capture: 5
        post_capture: 5
        retain:
          days: 7 # Any segment containing useful detection will be retained for 7 days.
          mode: motion

version: 0.17-0
